spring:
  application:
    name: ASE-UserService
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sau
          jwk-set-uri: http://localhost:8080/realms/sau/protocol/openid-connect/certs
server:
  port: 8081
  error:
    include-message: always
