apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading-service
  namespace: ase-12
  labels:
    app.kubernetes.io/name: grading-service
    app.kubernetes.io/instance: grading-service
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: grading-service
      app.kubernetes.io/instance: grading-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grading-service
        app.kubernetes.io/instance: grading-service
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: <pull-secret-name> # e.g. ghrc-secret for GHCR
      containers:
        - name: app
          image: ghcr.io/agile-software-engineering-25/grading-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/grading-service" # App will live under /<team>

            # Tell Spring to respect X-Forwarded-* from Traefik
            - name: SERVER_FORWARD_HEADERS_STRATEGY
              value: "framework"

            # Reasonable JVM sizing for containers (tune per app)
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50 -Djava.security.egd=file:/dev/./urandom"

            # Expose only necessary actuator endpoints; prometheus requires micrometer-registry-prometheus
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,prometheus"
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true" # Adds /actuator/health/liveness & /readiness

            # Enable graceful shutdown at app level (align with terminationGracePeriodSeconds)
            - name: SERVER_SHUTDOWN
              value: "graceful"

          readinessProbe:
            httpGet:
              path: /ase-12/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /ase-12/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /ase-12/actuator/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 30

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true # Immutable root FS → mount /tmp as writable
            capabilities:
              drop: ["ALL"]

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
