name: deploy-to-k8s

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Upload image
        uses: Agile-Software-Engineering-25/build-and-publish-image@v1.0.0

      - name: Deploy to Namespace
        uses: Agile-Software-Engineering-25/deploy-to-k8s@v1.0.0
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ secrets.NAMESPACE }}
